import Image from "next/image";
import Link from "next/link";
import ButtonLink from "@/components/ui/ButtonLink";
import Container from "@/components/ui/Container";
import SectionIntro from "@/components/ui/SectionIntro";

const applications = [
  ["Reparto de última milla", "Plataformas de motos eléctricas para evaluar operaciones comerciales de reparto y rutas."],
  ["Movilidad comercial urbana", "Plataformas para evaluar movilidad urbana, flotas de servicio y aplicaciones de transporte comercial."],
  ["Operaciones utilitarias y de servicio", "Plataformas comerciales para evaluar aplicaciones utilitarias y tareas de servicio."],
  ["Programas para distribuidores e importadores", "Evaluación de plataformas, requisitos de marca y planificación de suministro para socios comerciales."],
] as const;

const platforms = [
  { name: "Delivery X1", label: "Reparto / Última milla", href: "/es/productos/delivery-x1", image: "/images/products/Delivery/X1/02_Product/KIMI_Delivery_X1_Product_Card.webp", alt: "Moto eléctrica comercial KIMI Delivery X1", linkLabel: "Ver plataforma" },
  { name: "Urban X1", label: "Movilidad urbana", href: "/products/urban-x1", image: "/images/products/Urban/X1/02_Product/urban-x1-product-card.webp", alt: "Moto eléctrica KIMI Urban X1", linkLabel: "Ver plataforma — página en inglés" },
  { name: "Utility X1", label: "Uso comercial utilitario", href: "/products/utility-x1", image: "/images/products/Utility/X1/02_Product/utility-x1-product-card.webp", alt: "Moto eléctrica comercial KIMI Utility X1", linkLabel: "Ver plataforma — página en inglés" },
] as const;

const processSteps = [
  ["Definición del mercado y aplicación", "Comprender el mercado de destino, el caso de uso y los requisitos comerciales."],
  ["Selección de plataforma", "Identificar plataformas KIMI pertinentes para la evaluación del proyecto."],
  ["Evaluación de configuración", "Analizar requisitos de producto, marca y configuración sujetos a la plataforma seleccionada."],
  ["Planificación comercial y de suministro", "Coordinar la planificación comercial, el empaque, la documentación y la preparación del suministro según el proyecto."],
] as const;

export default function LatinAmericaLandingEs() {
  return (
    <main>
      <section className="relative min-h-[46rem] overflow-hidden bg-[#101923] pt-[5.25rem] text-white">
        <Image alt="Motos eléctricas comerciales KIMI para proyectos en mercados de América Latina" className="absolute inset-0 h-full w-full object-cover object-[58%_center]" fill priority sizes="100vw" src="/images/products/Delivery/X1/01_Hero/KIMI_Delivery_X1_Hero_V1.webp" unoptimized />
        <div className="absolute inset-0 bg-black/45 [background:linear-gradient(90deg,rgba(0,0,0,.84)_0%,rgba(0,0,0,.6)_44%,rgba(0,0,0,.12)_80%)]" />
        <Container className="relative flex min-h-[calc(46rem-5.25rem)] items-end pb-16 pt-20 sm:pb-20 lg:items-center lg:pb-0">
          <div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-kimi-green">América Latina</p><h1 className="mt-6 text-[length:var(--text-display)] font-semibold leading-[.96] tracking-[-0.055em]">Motos Eléctricas Comerciales para América Latina</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-white/68 sm:text-xl">KIMI trabaja con distribuidores, importadores y operadores de flotas que evalúan plataformas de motos eléctricas para mercados de América Latina, con selección, configuración y planificación de suministro sujetas a cada proyecto.</p><div className="mt-9 flex flex-wrap gap-4"><ButtonLink href="/partners/distributors#distributor-rfq" size="large">Consultar un proyecto de distribución — formulario en inglés</ButtonLink><ButtonLink href="/solutions/delivery-fleet#fleet-rfq" size="large" variant="secondary">Consultar un proyecto de flota — formulario en inglés</ButtonLink></div></div>
        </Container>
      </section>

      <section className="bg-white py-[var(--space-section)]"><Container className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-20"><SectionIntro eyebrow="Evaluación por mercado" title="Plataformas de movilidad eléctrica para mercados comerciales." /><div className="space-y-6 text-[length:var(--text-lead)] leading-relaxed text-kimi-black/58"><p>Las condiciones operativas, los requisitos comerciales y el entorno de uso varían entre países, mercados y aplicaciones. Cada proyecto debe evaluarse según su uso diario previsto, entorno operativo y necesidades del negocio.</p><p>La regulación, el registro, la homologación y los requisitos de importación varían según el destino. La configuración debe evaluarse de acuerdo con la plataforma y el proyecto, y las opciones disponibles pueden variar.</p><Link className="inline-flex font-semibold text-kimi-black underline decoration-kimi-green decoration-2 underline-offset-4" href="/es/mercados/colombia">Consultar el enfoque específico para Colombia</Link></div></Container></section>

      <section className="bg-[#f2f2f0] py-[var(--space-section)]"><Container><SectionIntro eyebrow="Aplicaciones comerciales" title="Evaluación basada en el trabajo que requiere cada mercado." /><div className="mt-14 grid border-l border-t border-kimi-black/15 md:grid-cols-2">{applications.map(([title, description], index) => <article className="border-b border-r border-kimi-black/15 p-7 sm:p-10" key={title}><span className="text-xs font-semibold tracking-[0.18em] text-kimi-green">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-8 text-2xl font-semibold tracking-[-0.035em]">{title}</h2><p className="mt-4 max-w-md leading-7 text-kimi-black/58">{description}</p></article>)}</div></Container></section>

      <section className="bg-[#e9e9e6] py-[var(--space-section)]"><Container><SectionIntro eyebrow="Plataformas de producto" title="Plataformas para diferentes aplicaciones comerciales." /><div className="mt-14 grid gap-px bg-kimi-black/15 lg:grid-cols-3">{platforms.map((platform) => <Link className="group bg-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-kimi-green" href={platform.href} key={platform.name}><div className="aspect-[4/3] overflow-hidden bg-[#f2f2f0]"><Image alt={platform.alt} className="h-full w-full object-contain transition-transform duration-500 group-hover:scale-[1.025]" height={900} loading="lazy" sizes="(min-width:1024px) 33vw, 100vw" src={platform.image} unoptimized width={1200} /></div><div className="p-7 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-kimi-green">{platform.label}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">{platform.name}</h2><span className="mt-7 inline-flex items-center gap-4 text-xs font-semibold uppercase tracking-[0.18em]">{platform.linkLabel}<span aria-hidden="true" className="h-px w-10 bg-kimi-green" /></span></div></Link>)}</div></Container></section>

      <section className="bg-kimi-black py-[var(--space-section)] text-white"><Container className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div className="overflow-hidden bg-[#202426]"><Image alt="Vista lateral de Delivery X1 para proyectos comerciales de reparto" className="h-auto w-full" height={1122} loading="lazy" sizes="(min-width:1024px) 52vw, 100vw" src="/images/products/Delivery/X1/02_Product/KIMI_Delivery_X1_Side_View_V1.webp" unoptimized width={1402} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-kimi-green">Reparto y flotas</p><h2 className="mt-5 text-[length:var(--text-heading)] font-semibold leading-[1.02] tracking-[-0.05em]">Evalúe el caso operativo antes de la configuración.</h2><p className="mt-7 text-[length:var(--text-lead)] leading-relaxed text-white/58">Las rutas, la carga, el entorno operativo y el uso diario previsto deben orientar la evaluación. La configuración está sujeta a la plataforma seleccionada y a los requisitos del proyecto.</p><ButtonLink className="mt-9" href="/es/soluciones/flota-reparto" size="large">Ver soluciones para flotas de reparto</ButtonLink></div></Container></section>

      <section className="bg-white py-[var(--space-section)]"><Container className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:gap-20"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-kimi-green">Distribuidores e importadores</p><h2 className="mt-5 text-[length:var(--text-heading)] font-semibold leading-[1.02] tracking-[-0.05em]">Planifique el producto y el suministro según el mercado.</h2></div><div><p className="text-[length:var(--text-lead)] leading-relaxed text-kimi-black/58">La selección de plataforma, los requisitos de marca, la planificación comercial, el empaque y la preparación para exportación pueden revisarse según el mercado y el proyecto. La documentación y la coordinación de envíos internacionales permanecen sujetas a los requisitos del proyecto.</p><div className="mt-9 flex flex-wrap gap-4"><ButtonLink href="/es/socios/distribuidores" size="large" variant="dark">Ver cooperación con distribuidores</ButtonLink><ButtonLink href="/es/oem" size="large" variant="secondary">Evaluar OEM y marca privada</ButtonLink></div></div></Container></section>

      <section className="bg-[#f2f2f0] py-[var(--space-section)]"><Container><SectionIntro eyebrow="Del mercado al suministro" title="Un enfoque de evaluación sujeto a cada proyecto." /><ol className="mt-14 grid border-l border-t border-kimi-black/15 md:grid-cols-2 lg:grid-cols-4">{processSteps.map(([title, description], index) => <li className="border-b border-r border-kimi-black/15 p-7 sm:p-8" key={title}><span className="text-sm font-semibold tracking-[0.18em] text-kimi-green">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-8 text-2xl font-semibold tracking-[-0.035em]">{title}</h2><p className="mt-4 leading-7 text-kimi-black/58">{description}</p></li>)}</ol><p className="mt-8 max-w-5xl border-l-2 border-kimi-green pl-5 text-sm leading-6 text-kimi-black/58">Los requisitos regulatorios, de homologación, registro, importación y circulación deben ser confirmados para cada mercado de destino por el comprador o importador, con apoyo profesional local debidamente calificado.</p></Container></section>

      <section className="bg-[#15191b] py-[var(--space-section)] text-white"><Container><SectionIntro align="center" eyebrow="Rutas para el proyecto" inverse title="Elija el camino correspondiente a su evaluación regional." /><div className="mx-auto mt-12 grid max-w-5xl gap-px bg-white/15 md:grid-cols-2"><div className="bg-kimi-black p-8 text-center sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/48">Distribuidor / Importador</p><ButtonLink className="mt-7" href="/partners/distributors#distributor-rfq" size="large">Consultar un proyecto de distribución — formulario en inglés</ButtonLink></div><div className="bg-kimi-black p-8 text-center sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/48">Operador de flota / Reparto</p><ButtonLink className="mt-7" href="/solutions/delivery-fleet#fleet-rfq" size="large" variant="light">Consultar un proyecto de flota — formulario en inglés</ButtonLink></div></div></Container></section>
    </main>
  );
}
